[[redirects]]
  from = "/api/*"
  to = "https://picture-diary.site:3000/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "yarn build"
