
[[redirects]]
  from = "/api/*"
  to = "http://118.67.142.166/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[build]
  publish = "dist"
  command = "yarn build"
