[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "http://118.67.142.166/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[build]
  publish = "dist"
  command = "yarn build"
